version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
    ignore:
      - dependency-name: "eslint"
        versions: ["8.x"]
      - dependency-name: "jest"
      # the following are locked to Expo and will be updated along with it
      - dependency-name: "@babel/core"
      - dependency-name: "@expo/webpack-config"
      - dependency-name: "babel-core"
      - dependency-name: "babel-jest"
      - dependency-name: "expo-secure-store"
      - dependency-name: "expo-status-bar"
      - dependency-name: "jest-expo"
      - dependency-name: "react"
      - dependency-name: "react-dom"
      - dependency-name: "react-native"
      - dependency-name: "react-native-gesture-handler"
      - dependency-name: "react-native-reanimated"
      - dependency-name: "react-native-safe-area-context"
      - dependency-name: "react-native-screens"
      - dependency-name: "react-native-web"
      - dependency-name: "typescript"
